server:
  port: ${PORT:8182}
  tomcat:
    max-swallow-size: -1

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: ${DATABASE_USER:dev}
    password: ${DATABASE_PASSWORD:dev}
    driver-class-name: org.h2.Driver
    tomcat:
      validation-query: SELECT 1
      test-on-borrow: true

camunda:
  bpm:
    admin-user:
      id: ${CAMUNDA_USER_ID:demo}
      password: ${CAMUNDA_USER_PASSWORD:demo}
      firstName: ${CAMUNDA_USER_FIRSTNAME:demo}
    filter:
      create: All tasks
